Const $LINEADDRESSTYPE_PHONENUMBER = "&H1"
Const $LINEMEDIAMODE_INTERACTIVEVOICE = "&H4"
Const $TAPI3_ALL_TAPI_EVENTS = "&H1FFFF"
Local  $lAddressType = $LINEADDRESSTYPE_PHONENUMBER

Local $txtAddressName = "LineName" ;Name of Line
Local $Number = "123456" ; Number to call

$objTapi = ObjCreate("TAPI.TAPI.1")
$mapper = ObjCreate("DispatchMapper.DispatchMapper.1")
$objTapi.Initialize
$objTapi.EventFilter = $TAPI3_ALL_TAPI_EVENTS
    
$objCollAddresses = $objTapi.Addresses
For $lLoop = 1 To $objCollAddresses.Count
    $objCrtAddress = $objCollAddresses.Item($lLoop)
    If $objCrtAddress.AddressName = $txtAddressName Then
        $gobjAddress = $objCrtAddress
        $bolFoundLine = True
        ExitLoop
    EndIf
Next

If $bolFoundLine = True Then
    $TestCall = $gobjAddress.CreateCall($Number, $lAddressType, $LINEMEDIAMODE_INTERACTIVEVOICE)
    $TestCall.connect(False)
EndIf
